### PR TITLE
Update to Ratchet 0.3.*

### PR DESCRIPTION
**Pull request by peshi**
Use the most current version of Ratchet.
Currently in use 0.2.7

### CODE REVIEW

**Comment by cboden** [comment]
There are [backwards compatibility breaks in 0.3](https://github.com/cboden/Ratchet/releases/tag/v0.3.0). 

> break: Decoupled HTTP from WebSocket component -> Ratchet\Http\HttpServer

The [WsServer instantiation](https://github.com/JDare/ClankBundle/blob/master/Server/Type/WebSocketServerType.php#L98) will need to be wrapped in a `Ratchet\Http\HttpServer` instance.

**Comment by peshi** [comment]
@cboden Thanks for pointing this out, i'll set it up locally and see if I can create a PR soon.

**Comment by peshi** [comment]
I'm going to close this, so that it doesn't linger while looking at bc break.

**Comment by bobvandevijver** [comment]
Any progress on the update to support `0.3.*`?

**Pull request closed without merging**
